<?php  
header('HTTP/1.0 403 Forbidden', true, 403);
require_once(substr(dirname(__FILE__),0,strpos(dirname(__FILE__), '/page-errors'))."/core/session.php");
echo '<!DOCTYPE html><html lang="en">'
.'<head>'
  .'<meta charset="utf-8"><meta content="width=device-width, initial-scale=1.0" name="viewport"><title> </title>'
  .'<link href="/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet">'
  .'<link href="/assets/Lock/lockstyle.css" rel="stylesheet">'
.'</head>'
.'<body>'
  .'<header id="header" class="fixed-top ">'
    .'<div class="container d-flex align-items-center">'
      .'<h1 class="logo me-auto"><a href="https://bss-online.it" target="_blank">BSS</a></h1>'
      .'<nav id="navbar" class="navbar"><ul><li><a class="nav-link scrollto" href="https://bss-online.it/contatti" target="_blank">Contatti</a></li></ul></nav></div>'
  .'</header>'           
  .'<section id="main" class="d-flex align-items-center">'
    .'<div class="container"><div class="row">'
        .'<div class="col-lg-6 d-flex flex-column justify-content-center pt-4 pt-lg-0 order-2 order-lg-1" >'
            .'<h1>403</h1>'
            .'<h2>Accesso negato</h2>'
            .'<h3>Permessi insufficienti per accedere ai contenuti o a una pagina specifica del sito web</h3>'
        .'</div>'
        .'<div class="col-lg-6 order-1 order-lg-2 main-img" >'
          .'<img src="/assets/Lock/img/403.webp" class="img-fluid animated" alt="">'
        .'</div>'
      .'</div>'
    .'</div>'
  .'</section>'         
  .'<footer id="footer">'
    .'<div class="container footer-bottom clearfix">'
      .'<div class="copyright">'
        .'&copy; Copyright ©<script>document.write(new Date().getFullYear());</script> <strong><span>BSS</span></strong>. All Rights Reserved'
      .'</div>'
      .'<div class="credits"></div>'
    .'</div>'
  .'</footer>'
  .'<div id="preloader"></div>'
  .'<script src="/assets/bootstrap/js/bootstrap.bundle.min.js"></script>'
  .'<script src="/assets/Lock/lockmain.js"></script>'
.'</body>'
.'</html>';